name: PUBlISH @k8ts/instruments
env:
  WORKSPACE: "@k8ts/instruments"
on:
  push:
    branches:
      - master
    paths:
      - "packages/instruments/**"
      - ".github/workflows/instruments.push.yaml"
      - "yaml.lock"
      - ".*"
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.9.0
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP COREPACK
        run: corepack enable

      - name: SETUP NODE.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: SETUP YARN
        run: yarn set version stable

      - name: INSTALL
        run: yarn install --immutable

      - name: BUILD
        run: yarn workspaces foreach -Rpt run build

      - name: LINT
        run: yarn workspace $WORKSPACE run lint:check

      - name: TEST
        run: yarn workspace $WORKSPACE run test

      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v4.2.0
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     directory: packages/parjs/coverage
      #     flags: parjs
      - name: SETUP PUBLISH TOKEN
        run: 'echo "npmAuthToken: ${NPM_TOKEN}" >> ~/.yarnrc.yml'

      - name: PUBLISH PACKAGE
        working-directory: packages/$WORKSPACE
        run: yarn npm publish --access public
