name: PR (any)
env:
  NODE_VERSION: "22.18.0"
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP COREPACK
        run: corepack enable

      - name: SETUP NODE.JS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: SETUP YARN
        run: yarn set version stable

      - name: INSTALL
        run: yarn workspaces focus workspace

      - name: LINT
        run: yarn run lint:check

  build_test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - workspace: "@k8ts/instruments"
          - workspace: k8ts
          - workspace: "@k8ts/metadata"
          - workspace: "@k8ts/sample-interfaces"
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP COREPACK
        run: corepack enable

      - name: SETUP NODE.JS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: SETUP YARN
        run: yarn set version stable

      - name: INSTALL
        run: yarn workspaces focus workspace ${{ matrix.workspace }}

      - name: BUILD
        run: yarn workspace ${{ matrix.workspace }} run build

      - name: TEST
        run: yarn workspace ${{ matrix.workspace }} run test

      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v4.2.0
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     plugin: noop
      #     directory: packages/char-info/coverage
      #     flags: char-info

      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v4.2.0
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     directory: packages/parjs/coverage
      #     flags: parjs
      #     plugin: noop
